Interdisciplinary/Interdisciplinary/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Interdisciplinary.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
    [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Interdisciplinary/Interdisciplinary/Controllers/DrinksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Interdisciplinary.Models;
using Interdisciplinary.Models.ViewModels;
using Interdisciplinary.Data;
using Microsoft.EntityFrameworkCore;
using Interdisciplinary.Infrastructure;

namespace Interdisciplinary.Controllers
{
    public class DrinksController : Controller
    {
        private ApplicationDbContext dataContext;
        private DrinksListViewModel drinks = new DrinksListViewModel();
        private List<DrinkIngredient> ids;
        public DrinksController(ApplicationDbContext dbContext)
        {
            dataContext = dbContext;
        }


        public IActionResult Index() {
            DrinksListViewModel DrinksList = GetList();
            if (DrinksList == null)
            {
                DrinksList = new DrinksListViewModel();
                DrinksList.Drinks = new List<DrinkViewModel>();
            }
            return View(DrinksList);}

        [HttpPost]
        public IActionResult Index(IEnumerable<string> selected)
        {

            drinks.Drinks = new List<DrinkViewModel>();
            string ingredientIds = string.Join(",", selected);
            ids = dataContext.DrinkIngredients.FromSqlRaw($"SELECT * from DrinkIngredients where IngredientId in ({ingredientIds})").ToList();

            foreach (DrinkIngredient drinkid in ids) {
                int id = drinkid.DrinkId;
                List<DrinksToIngredients> ingredients = dataContext.DrinksToIngredients.FromSqlRaw<DrinksToIngredients>($"SELECT * from DrinksToIngredientsView where DrinkId = {id}").ToList();
                DrinkViewModel drink = new DrinkViewModel();
                drink.DrinkId = id;
                
                drink.Ingredients = new List<DrinksToIngredients>();
                foreach(DrinksToIngredients e in ingredients)
                {
                    drink.Ingredients.Add(e);
                    drink.DrinkName = e.DrinkName;
                }
                drinks.Drinks.Add(drink);
                    }


            SaveList(drinks);


            return View(drinks);


        }


        private DrinksListViewModel GetList() { 
            DrinksListViewModel DrinksList = HttpContext.Session.GetJson<DrinksListViewModel>("DrinksList"); 
            return DrinksList; 
        }

        private void SaveList(DrinksListViewModel DrinksList) 
        { 
            HttpContext.Session.SetJson("DrinksList", DrinksList); 
        }








    }
}

Interdisciplinary/Interdisciplinary/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Interdisciplinary.Data;
using Interdisciplinary.Models;
using Interdisciplinary.Models.ViewModels;

namespace Interdisciplinary.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext dataContext;
        private FridgeViewModel fridge = new FridgeViewModel();

        public HomeController(ApplicationDbContext dbContext)
        {
            dataContext = dbContext;
        }

        public IActionResult Index()
        {

            fridge.Ingredients = dataContext.Ingredients;
            return View(fridge);


        }

        public IActionResult AddIngredient()
        {
            //fridge.ChosenIngredient.add()
            return View(fridge);


        }
        public IActionResult Wheel()
        {
            return View();
        }
        public IActionResult Random()
        {
            return View();
        }


    }
}

Interdisciplinary/Interdisciplinary/Controllers/RandomController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Interdisciplinary.Controllers
{
    public class RandomController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Interdisciplinary/Interdisciplinary/Views/Home/Index.cshtml
@using Interdisciplinary.Models;
@model FridgeViewModel
@{
    ViewData["Title"] = "Fridge";
}
<h1>@ViewData["Title"]</h1>

<form action="" method="post" id="IngredientPicker">
    <label class="rubrik" for="ingridiens">Choose your ingredients</label>
    <br />
    <select class="drink-select" id="ingridiens" name="ingredient">
        <option class="option" disabled> Choose ingredients</option>
        <optgroup label="Alcohol">

            @foreach (Ingredient ingredient in Model.Ingredients)
            {
                if (ingredient.CategoryId == 1)
                {
                    <option data-value='[{"name":"@ingredient.Name","id": "@ingredient.IngredientId", "category": "@ingredient.CategoryId"}]'>
                        @ingredient.Name
                    </option>
                }
            }
        </optgroup>
        <optgroup label="Garnish">
            @foreach (Ingredient ingredient in Model.Ingredients)
            {
                if (ingredient.CategoryId == 3)
                {
                    <option data-value='[{"name":"@ingredient.Name","id": "@ingredient.IngredientId", "category": "@ingredient.CategoryId"}]'>
                        @ingredient.Name
                    </option>
                }
            }
        </optgroup>
        <optgroup label="Softdrink">
            @foreach (Ingredient ingredient in Model.Ingredients)
            {
                if (ingredient.CategoryId == 2)
                {
                    <option data-value='[{"name":"@ingredient.Name","id": "@ingredient.IngredientId", "category": "@ingredient.CategoryId"}]'>
                        @ingredient.Name
                    </option>
                }
            }
        </optgroup>
    </select>
    <button class="button" type="submit">Add ingredient</button>
    <br />
</form>

<form asp-controller="Drinks" method="post" id="ChosenIngredients" asp-action="Index">
    <div class="chosen"></div>
    <button class="button" type="button"> Find exsisting cocktails</button>
</form>

<form method="post" id="getRandom" asp-controller="Random" asp-action="Index">
    <button class="button randomDrinkSubmit" type="button"> Generate your own custom cocktail</button>
</form>
<p class="error-message"></p>
<script src="~/js/site.js" asp-append-version="true"></script>

Interdisciplinary/Interdisciplinary/Views/Home/Wheel.cshtml
@{
    ViewData["Title"] = "Spin the Wheel";
}
<h1>@ViewData["Title"]</h1>


<h1>Who drinks?</h1>
@*<p id="list" style="font-size: 15px; font-weight: bold;">
</p>

<label for="players">Add more players?</label>
<input id="players" />
<button type="submit">Add</button>
<br />

<button class="button" id="button" onclick="randomName()">Spin the Wheel</button>

<p id="drink" style="font-size: 24px; font-weight: bold; color: #D56868;">
</p>*@


<div class="container">
    <div class="control">
        <br> <input class="button" autocomplete="off" type="text" id="input" placeholder="Enter names here"> <button class="button" id="addButton"> Add </button> <button class="button" id="shuffleButton"> Pick winner </button>
    </div>
    <div id="mother">

    </div>
    <div class="winner">
        <h3 class="winner_is">The victim is: <br> <span id="name"></span></h3>
    </div>
</div>

<script src="~/js/random.js" asp-append-version="true"></script>